version: "3.9"

services:
    link-folder:
        build: .
        container_name: linkFolder
        volumes:
            - .:/home/node/app
        ports:
            - 4200:4200
            - 3333:3333
        networks:
            - linkfoldernet
        restart: unless-stopped
        command: bash -c "npm run start"
        depends_on:
          - dbLF
        logging:
          options:
            max-size: "3m"
            max-file: "5"
    dbLF:
        image: mariadb
        container_name: dbLF
        environment:
          MARIADB_USER: ${DB_USER}
          MARIADB_PASSWORD: ${DB_PASSWORD}
          MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
          MARIADB_DATABASE: ${DB_NAME}
        volumes:
            - linkfolderDb:/var/lib/mysql
        ports:
            - 3336:3306
        networks:
            - linkfoldernet
        restart: unless-stopped
networks:
    linkfoldernet:
        name: linkfoldernet
volumes:
    linkfolderDb:
        name: linkfolderDb
